### ISSUE TITLE
Review Codec

### ISSUE THREAD

**Issue by julianhelpertz** [JenvyDevelopment/Haitatsu#8]
### Feedback

Please review the overall **project structure** and especially the **codec package** and provide _feedback_.

For explanation due to the missing documentation, just drop a message. 😉 

For feedback just open a new **issue** and assign it to the HaitatsuTodo project.

**Comment by madebyfusion** [comment]
I'll take a look, a few points I can point out already.
- Commit messages should be more unified and follow [this](https://www.conventionalcommits.org/de/v1.0.0/) guidelines.
- A few formatting / styling issues, but that's subjective to me. I'll open a PR later to discuss changes.

**Comment by julianhelpertz** [comment]
I will move the Jetbrains annotations to the API part of the application, so all subclasses got the Annotations.
Also, I took a look into the conventional commit guidelines, and I think I will use them for further commits.

Thanks for the feedback.
